#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FTJL.Resource", IsApplication=true)]

namespace FTJL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int loading = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070003
			public const int SampMode = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int SampUtile = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int SampYshi = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int SystemType = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int extraGoods = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int measureType = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int loading0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int loading1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int loading2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090020
			public const int Text = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int Text1 = 2131296289;
			
			// aapt resource value: 0x7f09005f
			public const int bAddUser = 2131296351;
			
			// aapt resource value: 0x7f090055
			public const int bAfterQuality = 2131296341;
			
			// aapt resource value: 0x7f090054
			public const int bBeforeQuality = 2131296340;
			
			// aapt resource value: 0x7f090061
			public const int bDelUser = 2131296353;
			
			// aapt resource value: 0x7f090062
			public const int bExit = 2131296354;
			
			// aapt resource value: 0x7f09003a
			public const int bLogin = 2131296314;
			
			// aapt resource value: 0x7f090060
			public const int bModifyUser = 2131296352;
			
			// aapt resource value: 0x7f090043
			public const int bagCount = 2131296323;
			
			// aapt resource value: 0x7f090059
			public const int boxCode = 2131296345;
			
			// aapt resource value: 0x7f090046
			public const int btExtract = 2131296326;
			
			// aapt resource value: 0x7f09001d
			public const int btGet = 2131296285;
			
			// aapt resource value: 0x7f090045
			public const int btNoExtra = 2131296325;
			
			// aapt resource value: 0x7f09000f
			public const int btReadic = 2131296271;
			
			// aapt resource value: 0x7f090018
			public const int btSamp = 2131296280;
			
			// aapt resource value: 0x7f09003d
			public const int btSamp2 = 2131296317;
			
			// aapt resource value: 0x7f09003e
			public const int btSampExtra = 2131296318;
			
			// aapt resource value: 0x7f090064
			public const int btSampSure = 2131296356;
			
			// aapt resource value: 0x7f090010
			public const int btSamplecar = 2131296272;
			
			// aapt resource value: 0x7f09001f
			public const int btSave = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int btSet = 2131296286;
			
			// aapt resource value: 0x7f090063
			public const int btSupplement = 2131296355;
			
			// aapt resource value: 0x7f090065
			public const int btTm = 2131296357;
			
			// aapt resource value: 0x7f090032
			public const int buAllReturn = 2131296306;
			
			// aapt resource value: 0x7f090031
			public const int buHalfReturn = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int buUnLoad = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int buUnloadAndLoad = 2131296307;
			
			// aapt resource value: 0x7f090040
			public const int cMeasureId = 2131296320;
			
			// aapt resource value: 0x7f09001a
			public const int carNumber = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int checkBox1 = 2131296279;
			
			// aapt resource value: 0x7f09002f
			public const int eBuckleWeight = 2131296303;
			
			// aapt resource value: 0x7f090044
			public const int extractBags = 2131296324;
			
			// aapt resource value: 0x7f090048
			public const int extractNumber = 2131296328;
			
			// aapt resource value: 0x7f090058
			public const int feedOpen = 2131296344;
			
			// aapt resource value: 0x7f090068
			public const int ghTm = 2131296360;
			
			// aapt resource value: 0x7f090023
			public const int goodsName = 2131296291;
			
			// aapt resource value: 0x7f090036
			public const int imageView1 = 2131296310;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout2 = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout3 = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int linearLayout4 = 2131296270;
			
			// aapt resource value: 0x7f090019
			public const int linearLayout5 = 2131296281;
			
			// aapt resource value: 0x7f09000d
			public const int linearLayout6 = 2131296269;
			
			// aapt resource value: 0x7f09003c
			public const int linearLayout7 = 2131296316;
			
			// aapt resource value: 0x7f09001c
			public const int listView1 = 2131296284;
			
			// aapt resource value: 0x7f090034
			public const int loadingImageView = 2131296308;
			
			// aapt resource value: 0x7f090037
			public const int mSystemType = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int mUserName = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int mUserPassword = 2131296313;
			
			// aapt resource value: 0x7f09003b
			public const int relativeLayout6 = 2131296315;
			
			// aapt resource value: 0x7f09005b
			public const int sSystemList = 2131296347;
			
			// aapt resource value: 0x7f09005c
			public const int sUserList = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int sUserName = 2131296349;
			
			// aapt resource value: 0x7f09005e
			public const int sUserPassword = 2131296350;
			
			// aapt resource value: 0x7f09000a
			public const int sampAdress = 2131296266;
			
			// aapt resource value: 0x7f090042
			public const int sampCarNum = 2131296322;
			
			// aapt resource value: 0x7f090056
			public const int sampCode = 2131296342;
			
			// aapt resource value: 0x7f090014
			public const int sampCount = 2131296276;
			
			// aapt resource value: 0x7f090041
			public const int sampFactory = 2131296321;
			
			// aapt resource value: 0x7f090012
			public const int sampGoods = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int sampGoodsname = 2131296264;
			
			// aapt resource value: 0x7f090057
			public const int sampMaction = 2131296343;
			
			// aapt resource value: 0x7f090009
			public const int sampMode = 2131296265;
			
			// aapt resource value: 0x7f090049
			public const int sampName = 2131296329;
			
			// aapt resource value: 0x7f09000c
			public const int sampPeople = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int sampTime = 2131296267;
			
			// aapt resource value: 0x7f090013
			public const int sampYshi = 2131296275;
			
			// aapt resource value: 0x7f090022
			public const int sampadress = 2131296290;
			
			// aapt resource value: 0x7f090015
			public const int sampunilt = 2131296277;
			
			// aapt resource value: 0x7f090067
			public const int spinner = 2131296359;
			
			// aapt resource value: 0x7f090066
			public const int spinner3 = 2131296358;
			
			// aapt resource value: 0x7f09004a
			public const int superviseName = 2131296330;
			
			// aapt resource value: 0x7f090047
			public const int supplier = 2131296327;
			
			// aapt resource value: 0x7f09004c
			public const int tBussnise = 2131296332;
			
			// aapt resource value: 0x7f09004b
			public const int tCarInfo = 2131296331;
			
			// aapt resource value: 0x7f090050
			public const int tGoodWeight = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int tMeasureDT = 2131296337;
			
			// aapt resource value: 0x7f09004f
			public const int tMeasureID = 2131296335;
			
			// aapt resource value: 0x7f09004e
			public const int tMeasureMode = 2131296334;
			
			// aapt resource value: 0x7f09004d
			public const int tMeasureType = 2131296333;
			
			// aapt resource value: 0x7f090053
			public const int tPerson = 2131296339;
			
			// aapt resource value: 0x7f090052
			public const int tQualityType = 2131296338;
			
			// aapt resource value: 0x7f09005a
			public const int tSelectUser = 2131296346;
			
			// aapt resource value: 0x7f090011
			public const int textView1 = 2131296273;
			
			// aapt resource value: 0x7f090025
			public const int textView10 = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int textView11 = 2131296294;
			
			// aapt resource value: 0x7f090016
			public const int textView2 = 2131296278;
			
			// aapt resource value: 0x7f090002
			public const int textView3 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int textView4 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int textView5 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int textView6 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int textView7 = 2131296262;
			
			// aapt resource value: 0x7f09003f
			public const int textView8 = 2131296319;
			
			// aapt resource value: 0x7f090024
			public const int textView9 = 2131296292;
			
			// aapt resource value: 0x7f090028
			public const int tuBussnise = 2131296296;
			
			// aapt resource value: 0x7f090027
			public const int tuCarInfo = 2131296295;
			
			// aapt resource value: 0x7f09002c
			public const int tuGoodWeight = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int tuMeasureDT = 2131296301;
			
			// aapt resource value: 0x7f09002b
			public const int tuMeasureID = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int tuMeasureMode = 2131296298;
			
			// aapt resource value: 0x7f090029
			public const int tuMeasureType = 2131296297;
			
			// aapt resource value: 0x7f09002e
			public const int tuPerson = 2131296302;
			
			// aapt resource value: 0x7f090035
			public const int tv_loadingmsg = 2131296309;
			
			// aapt resource value: 0x7f09001b
			public const int username = 2131296283;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int baiHui = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommonSamp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ExtraBags = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InsideDish = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InsideViewaxml = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Limestone = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Load = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loading = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MetalListInfo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RandomSamp = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int RandomSmpp = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SampCm = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SampMaction = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SystemManager = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int trainInfoList = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TrainSamp = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Unload = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int YugaSamp = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int NoDB = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CustomDialog = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CustomProgressDialog = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int nfc_tech_filter = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
